# Generated by Django 4.2.3 on 2023-07-12 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
