# Generated by Django 4.2.1 on 2023-07-14 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_message_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='issue',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
